/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedMonitorsIndexRouteImport } from './routes/_authenticated/monitors/index'
import { Route as AuthenticatedMonitorsNewRouteImport } from './routes/_authenticated/monitors/new'
import { Route as AuthenticatedMonitorsMonitorIdIndexRouteImport } from './routes/_authenticated/monitors/$monitorId/index'
import { Route as AuthenticatedMonitorsMonitorIdEditRouteImport } from './routes/_authenticated/monitors/$monitorId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMonitorsIndexRoute =
  AuthenticatedMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitorsNewRoute =
  AuthenticatedMonitorsNewRouteImport.update({
    id: '/monitors/new',
    path: '/monitors/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitorsMonitorIdIndexRoute =
  AuthenticatedMonitorsMonitorIdIndexRouteImport.update({
    id: '/monitors/$monitorId/',
    path: '/monitors/$monitorId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitorsMonitorIdEditRoute =
  AuthenticatedMonitorsMonitorIdEditRouteImport.update({
    id: '/monitors/$monitorId/edit',
    path: '/monitors/$monitorId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/monitors/new': typeof AuthenticatedMonitorsNewRoute
  '/monitors/': typeof AuthenticatedMonitorsIndexRoute
  '/monitors/$monitorId/edit': typeof AuthenticatedMonitorsMonitorIdEditRoute
  '/monitors/$monitorId/': typeof AuthenticatedMonitorsMonitorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/monitors/new': typeof AuthenticatedMonitorsNewRoute
  '/monitors': typeof AuthenticatedMonitorsIndexRoute
  '/monitors/$monitorId/edit': typeof AuthenticatedMonitorsMonitorIdEditRoute
  '/monitors/$monitorId': typeof AuthenticatedMonitorsMonitorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/monitors/new': typeof AuthenticatedMonitorsNewRoute
  '/_authenticated/monitors/': typeof AuthenticatedMonitorsIndexRoute
  '/_authenticated/monitors/$monitorId/edit': typeof AuthenticatedMonitorsMonitorIdEditRoute
  '/_authenticated/monitors/$monitorId/': typeof AuthenticatedMonitorsMonitorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/dashboard'
    | '/settings'
    | '/monitors/new'
    | '/monitors/'
    | '/monitors/$monitorId/edit'
    | '/monitors/$monitorId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/dashboard'
    | '/settings'
    | '/monitors/new'
    | '/monitors'
    | '/monitors/$monitorId/edit'
    | '/monitors/$monitorId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/alerts'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/monitors/new'
    | '/_authenticated/monitors/'
    | '/_authenticated/monitors/$monitorId/edit'
    | '/_authenticated/monitors/$monitorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitors/': {
      id: '/_authenticated/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof AuthenticatedMonitorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitors/new': {
      id: '/_authenticated/monitors/new'
      path: '/monitors/new'
      fullPath: '/monitors/new'
      preLoaderRoute: typeof AuthenticatedMonitorsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitors/$monitorId/': {
      id: '/_authenticated/monitors/$monitorId/'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId/'
      preLoaderRoute: typeof AuthenticatedMonitorsMonitorIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitors/$monitorId/edit': {
      id: '/_authenticated/monitors/$monitorId/edit'
      path: '/monitors/$monitorId/edit'
      fullPath: '/monitors/$monitorId/edit'
      preLoaderRoute: typeof AuthenticatedMonitorsMonitorIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedMonitorsNewRoute: typeof AuthenticatedMonitorsNewRoute
  AuthenticatedMonitorsIndexRoute: typeof AuthenticatedMonitorsIndexRoute
  AuthenticatedMonitorsMonitorIdEditRoute: typeof AuthenticatedMonitorsMonitorIdEditRoute
  AuthenticatedMonitorsMonitorIdIndexRoute: typeof AuthenticatedMonitorsMonitorIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedMonitorsNewRoute: AuthenticatedMonitorsNewRoute,
  AuthenticatedMonitorsIndexRoute: AuthenticatedMonitorsIndexRoute,
  AuthenticatedMonitorsMonitorIdEditRoute:
    AuthenticatedMonitorsMonitorIdEditRoute,
  AuthenticatedMonitorsMonitorIdIndexRoute:
    AuthenticatedMonitorsMonitorIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
